name: Run CI

on:
  pull_request:

jobs:
  test:
    env:
      CLIENT_ID: "fake_client"
      CLIENT_SECRET: "fake_secret"
      BOT_TOKEN: "fake"
      SIGNING_SECRET: "also_fake"
      TZ: "US/Eastern"
      TESTING: "True"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install .[test]

      - name: Lint and Format src/
        run: |
          python -m black --check src/
          python -m isort --check src/
          python -m ssort --check src/
          python -m pylint --fail-under=10 src/

      - name: Lint and Format tests/
        run: |
          python -m black --check tests/
          python -m isort --check tests/
          python -m ssort --check tests/
          python -m pylint --fail-under=10 tests/

      - name: Pytest
        run: python -m pytest tests/
